# Welcome to Jekyll!
#

# Site settings
title: Tanner Fadero
description: <br>
  Graduate Researcher  <br>
  <a href="http://labs.bio.unc.edu/Maddox/Site/Welcome.html">Paul Maddox Lab</a><br>
  <a href="https://bio.unc.edu">Biology Department - UNC Chapel Hill</a><br>
owner: Tanner Fadero
first_published: 2019 # if migrating another site, the year of your first publish
email: tanner.fadero@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/tanfad
  github: https://github.com/fadero
  linkedin-square: https://www.linkedin.com/in/tanner-fadero/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:tanner.fadero@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
